[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
pytest-cov = "^4.0.0"
bandit = "^1.7.1"
black = ">=22.1.0"  # date based version numbering
isort = "^5.10.1"
flake8 = "^6.0.0"
flake8-black = "^0.3.3"
flake8-bugbear = ">=22.1.11"  # date based version numbering
flake8-docstrings = "^1.6.0"
flake8-print = "^5.0.0"
flake8-isort = "^6.0.0"
mypy = "^1.0.1"


[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = 3.11
namespace_packages = true
ignore_missing_imports = false
check_untyped_defs = true
no_implicit_optional = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true
warn_return_any = true
warn_unreachable = true
show_error_codes = true
plugins = [
  "pydantic.mypy"
]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = false
warn_required_dynamic_aliases = true
warn_untyped_fields = true
